[package]
name = "clipls"
version = "0.1.0"
edition = "2024"
description = "Copy files on the clipboard using a terminal interface"
license = "MIT"
repository = "https://github.com/h2depot/clipls"

[dependencies]
anyhow = "1.0.104"
arboard = { version = "3.6.1", default-features = false }
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.2"

[build-dependencies]
winresource = "0.1"

[[bin]]
name = "clipls"
path = "src/main.rs"
